### ISSUE TITLE
jaskson 데이터 파싱

### ISSUE THREAD

**Issue by jhkim31** [f-lab-edu/jshop#106]
<img width="1869" alt="스크린샷 2024-08-11 19 48 39" src="https://github.com/user-attachments/assets/1f2eeb01-53f7-4b3c-8491-446f56ad4be9">

쿠폰 생성 위해 날짜를 보내면, jackson 이 파싱을 하지 못하는 문제

```bash
2024-08-11 19:47:42.835 [http-nio-8080-exec-2] [ERROR] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class java.time.LocalDateTime]] with root cause 
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 8, column: 24] (through reference chain: jshop.core.domain.coupon.dto.CreateCouponRequest["issueStartDate"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1887)
	at com.fasterxml.jackson.databind.deser.impl.UnsupportedTypeDeserializer.deserialize(UnsupportedTypeDeserializer.java:48)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
```

**Comment by jhkim31** [comment]
`implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'` 추가
